/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#00e38b",
        "surface-container-highest": "#2e3446",
        "surface-container-low": "#141b2c",
        "on-tertiary-fixed": "#002022",
        "secondary-fixed": "#56ffa8",
        "tertiary-fixed": "#7df4ff",
        "tertiary-fixed-dim": "#00dbe9",
        "on-surface": "#dce2f9",
        "on-primary": "#450086",
        "error": "#ffb4ab",
        "on-surface-variant": "#cec2d8",
        "on-background": "#dce2f9",
        "background": "#0c1323",
        "outline-variant": "#4c4355",
        "on-secondary": "#00391f",
        "primary": "#d8b9ff",
        "surface-container-lowest": "#070e1e",
        "on-tertiary-fixed-variant": "#004f54",
        "secondary-container": "#00ec91",
        "surface-container-high": "#232a3b",
        "on-error": "#690005",
        "primary-fixed-dim": "#d8b9ff",
        "tertiary-container": "#00838c",
        "inverse-primary": "#7f21e5",
        "on-secondary-fixed-variant": "#00522f",
        "on-secondary-container": "#00653b",
        "surface-dim": "#0c1323",
        "on-tertiary-container": "#ffffff",
        "surface-bright": "#32394b",
        "on-primary-fixed": "#290055",
        "primary-fixed": "#eddcff",
        "on-primary-fixed-variant": "#6300bb",
        "surface-tint": "#d8b9ff",
        "primary-container": "#9945ff",
        "surface-container": "#181f30",
        "inverse-surface": "#dce2f9",
        "on-error-container": "#ffdad6",
        "secondary": "#a0ffc3",
        "on-primary-container": "#ffffff",
        "inverse-on-surface": "#293041",
        "outline": "#978da1",
        "surface-variant": "#2e3446",
        "on-secondary-fixed": "#002110",
        "on-tertiary": "#00363a",
        "tertiary": "#00dbe9",
        "surface": "#0c1323",
      },
      "fontFamily": {
        "label-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "display-lg": ["Space Grotesk"],
        "code-md": ["JetBrains Mono"],
        "headline-lg": ["Space Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Geist"],
        "headline-sm": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "body-sm": ["Geist"],
        "display-lg-mobile": ["Space Grotesk"],
        "body-lg": ["Geist"],
        "code-lg": ["JetBrains Mono"],
        "headline-lg-mobile": ["Space Grotesk"]
      },
      "fontSize": {
        "label-md": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "code-sm": ["0.6875rem", { "lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "display-lg": ["3rem", { "lineHeight": "3.5rem", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "code-md": ["0.8125rem", { "lineHeight": "1.375rem", "fontWeight": "400" }],
        "headline-lg": ["2rem", { "lineHeight": "2.5rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["0.625rem", { "lineHeight": "0.875rem", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-md": ["0.9375rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "headline-sm": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "600" }],
        "headline-md": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["0.8125rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "display-lg-mobile": ["2rem", { "lineHeight": "2.5rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "code-lg": ["0.9375rem", { "lineHeight": "1.5rem", "fontWeight": "500" }],
        "headline-lg-mobile": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
